---
- name: Install necessary apt packages
  apt:
    name: "{{ item }}"
  loop: "{{ pip3_apt_pkgs | default([]) }}"

- name: Update /usr/bin/python symlink to python3
  file:
    path: /usr/bin/python
    src: /usr/bin/python3
    state: link

- name: Update pip3 to latest
  pip:
    executable: pip3
    name: pip
    state: latest
  when: pip3_latest